// This file has been removed as part of payment/billing removal.
"use client";

import { useState } from "react";
import { useFirestore, useMemoFirebase, useCollection } from "@/firebase";
import { collection, addDoc, deleteDoc, query, orderBy, doc, updateDoc, writeBatch } from "firebase/firestore";
import { useUser } from "@/firebase";
import { isAdminEmail } from "@/lib/admin";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogFooter,
	DialogTitle,
	DialogClose,
} from "@/components/ui/dialog";

import type { CollectionReference } from "firebase/firestore";

const initialPlans = [
// USD plans
{
 id: 'lifetime',
 name: 'Lifetime Membership',
 price: 25,
 currency: 'USD',
 description: 'Permanent membership required to purchase any other plan. One-time payment, allows access to all other plans.',
 features: [
 'Personal onboarding with Z',
 'Resume intake & profile setup',
 'Expert profile review',
 'Fast, secure data handling',
 'Permanent membership (one-time payment)'
 ],
 category: 'membership',
 validity: 'lifetime',
},
{
 id: 'payg',
 name: 'Pay-As-You-Go',
 price: 0,
 currency: 'USD',
 description: 'Monthly postpaid plan. $2 per application, $3 per approved application. Bill is generated based on number of hot jobs applied and approved.',
 features: [
 'Z applies for you',
 '$2 per application',
 '$3 per approved application',
 'Live status tracking'
 ],
 category: 'service',
},
{
 id: 'pro_month_usd',
 name: 'Pro (One Month)',
 price: 500,
 currency: 'USD',
 description: 'Monthly plan for serious job hunters. Up to 300 hot jobs apply per month.',
 features: [
 'Up to 300 hot jobs applications/month',
 'Advanced resume tailoring',
 '1:1 onboarding call',
 'Priority support'
 ],
 category: 'service',
},
{
 id: 'elite_usd',
		name: 'Elite Add-Ons',
		price: 10000,
		currency: 'USD',
		description: 'Monthly plan. Premium features for maximum success. Bill generated by admin.',
		features: [
			'Ask Z: HR Q&A agent',
			'Resume AI chatbot',
			'Interview Cohort coaching',
			'Early access to new AI'
		],
		 category: 'service',
	},
	// INR plans
	{
		id: 'payg_inr',
		name: 'Pay-As-You-Go',
		price: 20,
		currency: 'INR',
		description: 'Monthly postpaid plan. ₹20 per application, ₹30 per approved application. Bill is generated based on number of hot jobs applied and approved.',
		features: [
			'Z applies for you',
			'₹20 per application',
			'₹30 per approved application',
			'Live status tracking'
		],
		 category: 'service',
	},
	{
		id: 'lifetime_inr',
		name: 'Lifetime Membership',
		price: 199,
		currency: 'INR',
		description: 'Permanent membership required to purchase any other plan. One-time payment, allows access to all other plans.',
		features: [
			'Personal onboarding with Z',
			'Resume intake & profile setup',
			'Expert profile review',
			'Fast, secure data handling',
			'Permanent membership (one-time payment)'
		],
		category: 'membership',
		validity: 'lifetime',
	},
	{
		id: 'pro_month',
		name: 'Pro (One Month)',
		price: 99,
		currency: 'INR',
		description: 'Monthly plan for serious job hunters. Up to 300 hot jobs apply per month.',
		features: [
			'Up to 300 hot jobs applications/month',
			'Advanced resume tailoring',
			'1:1 onboarding call',
			'Priority support'
		],
		 category: 'service',
	},
	{
		id: 'elite',
		name: 'Elite Add-Ons',
		price: 10000,
		currency: 'INR',
		description: 'Monthly plan. Premium features for maximum success. Bill generated by admin.',
		features: [
			'Ask Z: HR Q&A agent',
			'Resume AI chatbot',
			'Interview Cohort coaching',
			'Early access to new AI'
		],
		 category: 'service',
	},
];

export default function PlansAdminPage() {
	const { user } = useUser();
	const isAdmin = isAdminEmail(user?.email);
	const firestore = useFirestore();
	const plansCollection: CollectionReference | null = firestore ? collection(firestore, "plans") : null;
	const [refreshKey, setRefreshKey] = useState(0);
	const plansQuery = useMemoFirebase(
		() => (firestore ? query(collection(firestore, "plans")) : null),
		[firestore, refreshKey]
	);
	const { data: plansRaw = [], isLoading } = useCollection<any>(plansQuery);
	const plans = (plansRaw ?? []).map((plan: any, index: number) => ({ ...plan, __id: plan.__id || plan.id || plan.docId || "", position: plan.position ?? index }));
	const [newPlan, setNewPlan] = useState({
	 id: "",
	 name: "",
	 price: "",
	 currency: "USD",
	 category: "",
	 validity: "",
	 description: "",
	 features: "",
	 resumesLimit: "",
	 jobsLimit: "",
	 // note: removed
	 popular: false,
	 permissions: JSON.stringify({ allowApply: true, requireStarter: false, allowResume: true, allowEditApplications: true }),
	});
	const [editPlan, setEditPlan] = useState<any>(null);
	const [showAddDialog, setShowAddDialog] = useState(false);
	const [showEditDialog, setShowEditDialog] = useState(false);

	const handleUploadInitialPlans = async () => {
		if (plansCollection) {
			for (const plan of initialPlans) {
				await addDoc(plansCollection, plan);
			}
			alert("Initial plans uploaded to Firestore.");
		}
	};

	if (!isAdmin) {
		return <div className="p-8 text-center">Access denied. Admins only.</div>;
	}

	const handleAddPlan = async () => {
		const planToAdd = {
			...newPlan,
			 id: Date.now().toString(),
			 position: plans.length,
			 features: newPlan.features.split(",").map((f: string) => f.trim()),
			 permissions: newPlan.permissions || JSON.stringify({ allowApply: true, requireStarter: false, allowResume: true, allowEditApplications: true }),
		};
		if (plansCollection) {
			try {
				await addDoc(plansCollection, planToAdd);
				alert("Plan added successfully.");
			} catch (err: any) {
				alert("Error adding plan: " + err.message);
			}
		}
				setNewPlan({
				 id: "",
				 name: "",
				 price: "",
				 currency: "USD",
				 category: "",
				 validity: "",
				 description: "",
				 features: "",
				 resumesLimit: "",
				 jobsLimit: "",
				 // note: removed
				 popular: false,
				 permissions: JSON.stringify({ allowApply: true, requireStarter: false, allowResume: true, allowEditApplications: true }),
				 });
	};

	const handleUpdatePlan = async () => {
		if (!editPlan || !editPlan.__id) {
			alert("Error: Plan to update is not selected.");
			return;
		}
		   // Parse pricing if it's a string
		   let planToUpdate = {
			   ...editPlan,
			   features: Array.isArray(editPlan.features) ? editPlan.features : editPlan.features.split(",").map((f: string) => f.trim()),
		   };
		   if (typeof planToUpdate.pricing === 'string') {
			   if (planToUpdate.pricing.trim() === '') {
				   delete planToUpdate.pricing;
			   } else {
				   try {
					   planToUpdate.pricing = JSON.parse(planToUpdate.pricing);
				   } catch {
					   alert('Invalid JSON in Pricing field.');
					   return;
				   }
			   }
		   } else if (typeof planToUpdate.pricing === 'undefined') {
			   delete planToUpdate.pricing;
		   }
		   if (firestore) {
			   try {
				   await updateDoc(doc(firestore, "plans", editPlan.__id), planToUpdate);
				   setRefreshKey(k => k + 1); // force refresh
				   alert("Plan updated successfully.");
			   } catch (err: any) {
				   alert("Error updating plan: " + err.message);
			   }
		   }
		   setEditPlan(null);
		   setShowEditDialog(false);
	};

	const handleRemovePlan = async (docId: string) => {
		if (!docId) {
			alert("Error: Plan document id is missing.");
			return;
		}
		   if (firestore) {
			   try {
				   await deleteDoc(doc(firestore, "plans", docId));
				   setRefreshKey(k => k + 1); // force refresh
				   alert("Plan deleted successfully.");
			   } catch (err: any) {
				   alert("Error deleting plan: " + err.message);
			   }
		   }
	};

	return (
		<div className="p-4 lg:p-8">
			<div className="flex justify-between items-center mb-4">
				<h1 className="text-xl lg:text-2xl font-bold">Admin Plans</h1>
				<Button onClick={() => setShowAddDialog(true)} variant="default">Add Plan</Button>
			</div>
			
			{/* Responsive container for table */}
			<div className="w-full overflow-x-auto">
				<Table className="min-w-[800px]">
					<TableHeader>
						<TableRow>
							<TableHead className="min-w-[120px]">Plan Name</TableHead>
							<TableHead className="min-w-[80px]">Price</TableHead>
							<TableHead className="min-w-[80px]">Currency</TableHead>
							<TableHead className="min-w-[100px]">Category</TableHead>
							<TableHead className="min-w-[100px]">Validity</TableHead>
							<TableHead className="min-w-[150px]">Description</TableHead>
							<TableHead className="min-w-[200px]">Features</TableHead>
							<TableHead className="min-w-[100px]">Resumes Limit</TableHead>
							<TableHead className="min-w-[100px]">Jobs Limit</TableHead>
							{/* Popular and Permissions columns removed from table header */}
							<TableHead className="min-w-[120px]">Actions</TableHead>
						</TableRow>
					</TableHeader>
					<TableBody>
						{plans.map((plan) => (
							<TableRow key={plan.__id || plan.id}>
								<TableCell className="font-medium">{plan.name}</TableCell>
								<TableCell>{plan.price}</TableCell>
								<TableCell>{plan.currency}</TableCell>
								<TableCell>{plan.category ?? ''}</TableCell>
								<TableCell>{plan.validity ?? ''}</TableCell>
								<TableCell>
									<div className="max-w-[150px] break-words">
										{plan.description}
									</div>
								</TableCell>
								<TableCell>
									<div className="max-w-[200px] break-words">
										{Array.isArray(plan.features) ? plan.features.join(", ") : plan.features}
									</div>
								</TableCell>
								<TableCell>{plan.resumesLimit ?? plan.maxHotJobsApplications ?? plan.maxApplications ?? ''}</TableCell>
								<TableCell>{plan.jobsLimit ?? plan.maxHotJobs ?? ''}</TableCell>
								{/* Popular and Permissions data removed from table body */}
								<TableCell>
									<div className="flex flex-col gap-1">
										<Button size="sm" onClick={() => { setEditPlan(plan); setShowEditDialog(true); }}>Edit</Button>
										<Button size="sm" variant="destructive" onClick={() => handleRemovePlan(plan.__id || plan.id)}>Delete</Button>
									</div>
								</TableCell>
							</TableRow>
						))}
					</TableBody>
				</Table>
			</div>

			{/* Add Plan Dialog */}
			<Dialog open={showAddDialog} onOpenChange={setShowAddDialog}>
				<DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
					<DialogHeader>
						<DialogTitle>Add Plan</DialogTitle>
					</DialogHeader>
					<div className="space-y-2">
						 <input className="w-full border p-2" placeholder="Name" value={newPlan.name} onChange={e => setNewPlan({ ...newPlan, name: e.target.value })} />
						 <input className="w-full border p-2" placeholder="Price" value={newPlan.price} onChange={e => setNewPlan({ ...newPlan, price: e.target.value })} />
						 <select className="w-full border p-2" value={newPlan.currency} onChange={e => setNewPlan({ ...newPlan, currency: e.target.value })}>
						 <option value="USD">USD</option>
						 <option value="INR">INR</option>
						 </select>
						<select className="w-full border p-2" value={newPlan.category ?? ''} onChange={e => setNewPlan({ ...newPlan, category: e.target.value })}>
							<option value="">Select Category</option>
							<option value="membership">Membership</option>
							<option value="service">Service</option>
							<option value="addon">Addon</option>
						</select>
						 <select className="w-full border p-2" value={newPlan.validity ?? ''} onChange={e => setNewPlan({ ...newPlan, validity: e.target.value })}>
						 <option value="">Select Validity</option>
						 <option value="lifetime">Lifetime</option>
						 <option value="1 month">1 Month</option>
						 <option value="3 months">3 Months</option>
						 <option value="6 months">6 Months</option>
						 <option value="1 year">1 Year</option>
						 </select>
						 <input className="w-full border p-2" placeholder="Description" value={newPlan.description} onChange={e => setNewPlan({ ...newPlan, description: e.target.value })} />
						 <input className="w-full border p-2" placeholder="Features (comma separated)" value={newPlan.features} onChange={e => setNewPlan({ ...newPlan, features: e.target.value })} />
						<input className="w-full border p-2" placeholder="Resumes Limit" value={newPlan.resumesLimit ?? ''} onChange={e => setNewPlan({ ...newPlan, resumesLimit: e.target.value })} />
						<input className="w-full border p-2" placeholder="Jobs Limit" value={newPlan.jobsLimit ?? ''} onChange={e => setNewPlan({ ...newPlan, jobsLimit: e.target.value })} />
						<label className="flex items-center"><input type="checkbox" checked={newPlan.popular ?? false} onChange={e => setNewPlan({ ...newPlan, popular: e.target.checked })} /> Popular</label>
						 <input className="w-full border p-2" placeholder="Permissions (JSON)" value={newPlan.permissions ? JSON.stringify(newPlan.permissions) : ''} onChange={e => setNewPlan({ ...newPlan, permissions: e.target.value ? JSON.parse(e.target.value) : undefined })} />
					</div>
					<DialogFooter>
						<Button onClick={handleAddPlan}>Add</Button>
						<DialogClose asChild>
							<Button variant="secondary">Cancel</Button>
						</DialogClose>
					</DialogFooter>
				</DialogContent>
			</Dialog>

			{/* Edit Plan Dialog */}
			<Dialog open={showEditDialog} onOpenChange={setShowEditDialog}>
				   <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
					   <DialogHeader>
						   <DialogTitle>Edit Plan</DialogTitle>
					   </DialogHeader>
					   {editPlan && (
						   <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
							   <div>
								   <label className="block text-sm font-medium mb-1">Name</label>
								   <input className="w-full border p-2" placeholder="Name" value={editPlan.name} onChange={e => setEditPlan({ ...editPlan, name: e.target.value })} />
							   </div>
							 <div>
							 <label className="block text-sm font-medium mb-1">Price</label>
							 <input className="w-full border p-2" placeholder="Price" value={editPlan.price} onChange={e => setEditPlan({ ...editPlan, price: e.target.value })} />
							 </div>
							 <div>
							 <label className="block text-sm font-medium mb-1">Currency</label>
							 <select className="w-full border p-2" value={editPlan.currency} onChange={e => setEditPlan({ ...editPlan, currency: e.target.value })}>
							 <option value="USD">USD</option>
							 <option value="INR">INR</option>
							 </select>
							 </div>
							   <div>
								   <label className="block text-sm font-medium mb-1">Category</label>
								   <select className="w-full border p-2" value={editPlan.category ?? ''} onChange={e => setEditPlan({ ...editPlan, category: e.target.value })}>
									   <option value="">Select Category</option>
									   <option value="membership">Membership</option>
									   <option value="service">Service</option>
									   <option value="addon">Addon</option>
								   </select>
							   </div>
							   <div>
								   <label className="block text-sm font-medium mb-1">Plan Type</label>
								   <select className="w-full border p-2" value={editPlan.planType ?? ''} onChange={e => setEditPlan({ ...editPlan, planType: e.target.value })}>
									   <option value="">Select Type</option>
									   <option value="prepaid">Prepaid</option>
									   <option value="postpaid">Postpaid</option>
								   </select>
							   </div>
							   <div>
								   <label className="block text-sm font-medium mb-1">Validity</label>
								   <select className="w-full border p-2" value={editPlan.validity ?? ''} onChange={e => setEditPlan({ ...editPlan, validity: e.target.value })}>
									   <option value="">Select Validity</option>
									   <option value="lifetime">Lifetime</option>
									   <option value="1 month">1 Month</option>
									   <option value="3 months">3 Months</option>
									   <option value="6 months">6 Months</option>
									   <option value="1 year">1 Year</option>
								   </select>
							   </div>
							   <div className="md:col-span-2">
								   <label className="block text-sm font-medium mb-1">Description</label>
								   <input className="w-full border p-2" placeholder="Description" value={editPlan.description} onChange={e => setEditPlan({ ...editPlan, description: e.target.value })} />
							   </div>
							   <div className="md:col-span-2">
								   <label className="block text-sm font-medium mb-1">Features (comma separated)</label>
								   <input className="w-full border p-2" placeholder="Features (comma separated)" value={Array.isArray(editPlan.features) ? editPlan.features.join(", ") : editPlan.features} onChange={e => setEditPlan({ ...editPlan, features: e.target.value })} />
							   </div>
							   <div>
								 <label className="block text-sm font-medium mb-1">Resumes Limit</label>
								 <input className="w-full border p-2" placeholder="Resumes Limit" value={editPlan.resumesLimit ?? editPlan.maxHotJobsApplications ?? editPlan.maxApplications ?? ''} onChange={e => setEditPlan({ ...editPlan, resumesLimit: e.target.value })} />
								 <label className="block text-sm font-medium mb-1">Jobs Limit</label>
								 <input className="w-full border p-2" placeholder="Jobs Limit" value={editPlan.jobsLimit ?? editPlan.maxHotJobs ?? ''} onChange={e => setEditPlan({ ...editPlan, jobsLimit: e.target.value })} />
							   </div>
 
							   <div className="flex items-center space-x-2">
								   <input type="checkbox" checked={editPlan.popular ?? false} onChange={e => setEditPlan({ ...editPlan, popular: e.target.checked })} />
								   <label className="text-sm font-medium">Popular</label>
							   </div>
							 <div className="flex items-center space-x-2 md:col-span-2">
								 <input
									 type="checkbox"
									 checked={!!(editPlan.permissions && editPlan.permissions.allowHotJobsApply)}
									 onChange={e => {
										 let perms = editPlan.permissions || {};
										 if (typeof perms === 'string') {
											 try { perms = JSON.parse(perms); } catch { perms = {}; }
										 }
										 perms.allowHotJobsApply = e.target.checked;
										 setEditPlan({ ...editPlan, permissions: perms });
									 }}
								 />
								 <label className="text-sm font-medium">Allow Hot Jobs Apply</label>
							 </div>
						   </div>
					   )}
					   <DialogFooter className="mt-4">
						   <Button onClick={handleUpdatePlan}>Update</Button>
						   <DialogClose asChild>
							   <Button variant="secondary">Cancel</Button>
						   </DialogClose>
					   </DialogFooter>
				   </DialogContent>
			</Dialog>
		</div>
	);
}