// All plans (USD and INR, with currency field)
export const plans = [
  // USD plans
  {
    id: 'lifetime',
    name: 'Starter Onboarding',
    price: 25,
    priceNumeric: 25,
    currency: 'USD',
    description: 'Bi-yearly membership renewal. Keep profile, resume, and skills updated via 1:1 Z session.',
    features: [
      'Personal onboarding with Z',
      'Resume intake & profile setup',
      'Expert profile review',
      'Fast, secure data handling',
      'Bi-yearly membership renewal'
    ],
    billing: 'one-time',
    billingCycle: 'one-time',
    category: 'membership',
    validity: 'lifetime',
  },
  // USA plans
  {
    id: 'payg',
    name: 'Pay-As-You-Go',
    price: 'Monthly postpaid',
    currency: 'USD',
    description: 'Monthly postpaid plan. $2 per submission or $3 per priority submission.',
    features: [
      'Z applies for you',
      '$2 per submission',
      '$3 per priority submission',
      'Live status tracking',
      'Previous month invoice access',
      'Lifetime validity (after membership)'
    ],
    billing: 'monthly-postpaid',
    billingCycle: 'monthly',
    category: 'service',
    pricing: { perApplication: 2, perHotJob: 3, currency: 'USD' },
    dependsOn: 'lifetime',
    validity: 'lifetime',
  },
  {
    id: 'pro_month_usd',
    name: 'Pro (Monthly)',
    price: 500,
    currency: 'USD',
    description: 'Monthly auto-renewing plan for serious job hunters. Minimum 300 submissions per month with dedicated Z concierge.',
    features: [
      'Minimum 300 submissions/month',
      'Advanced resume tailoring',
      '1:1 onboarding call',
      'Dedicated Z Concierge'
    ],
    billing: 'monthly',
    billingCycle: 'monthly',
    category: 'service',
    dependsOn: 'lifetime',
  },
  {
    id: 'elite_usd',
    name: 'Elite Add-Ons',
    price: 10000,
    currency: 'USD',
    description: 'Monthly plan. Premium features for maximum success. Bill generated by admin.',
    features: [
      'Ask Z: HR Q&A agent',
      'Resume AI chatbot',
      'Interview Cohort coaching',
      'Early access to new AI'
    ],
    billing: 'monthly-admin',
    billingCycle: 'monthly',
    category: 'service',
    dependsOn: 'lifetime',
  },
  // INR plans
  {
    id: 'payg_inr',
    name: 'Pay-As-You-Go',
    price: 'wallet based',
    currency: 'INR',
    description: 'Wallet based plan you can activate your wallet and Top Up your wallet. ₹20 per application based on wallet balance  you can number of hot jobs applied.',
    features: [
      'Z applies for you',
      '₹20 per application',
      'Live status tracking'
    ],
    billing: 'monthly-postpaid',
    billingCycle: 'monthly',
    category: 'service',
    pricing: { perApplication: 20, currency: 'INR' },
    dependsOn: 'lifetime_inr',
  },
  // INR plans
  {
    id: 'lifetime_inr',
    name: 'Starter Onboarding',
    price: 999,
    priceNumeric: 999,
    currency: 'INR',
    description: 'Bi-yearly membership renewal. Keep profile, resume, and skills updated via 1:1 Z session.',
    features: [
      'Personal onboarding with Z',
      'Resume intake & profile setup',
      'Expert profile review',
      'Fast, secure data handling',
      'Bi-yearly membership renewal'
    ],
    billing: '1-year',
    billingCycle: 'one-year',
    category: 'membership',
    validity: '365 days',
  },
  {
    id: 'pro_month',
    name: 'Pro (Monthly)',
    price: 1999,
    currency: 'INR',
    description: 'Monthly auto-renewing plan for serious job hunters. Minimum 300 submissions per month with dedicated Z concierge.',
    features: [
      'Minimum 300 submissions/month',
      'Advanced resume tailoring',
      '1:1 onboarding call',
      'Dedicated Z Concierge'
    ],
    billing: 'monthly',
    billingCycle: 'monthly',
    category: 'service',
    dependsOn: 'lifetime_inr',
  },
  {
    id: 'elite',
    name: 'Elite Add-Ons',
    price: 10000,
    currency: 'INR',
    description: 'Monthly plan. Premium features for maximum success. Bill generated by admin.',
    features: [
      'Ask Z: HR Q&A agent',
      'Resume AI chatbot',
      'Interview Cohort coaching',
      'Early access to new AI'
    ],
    billing: 'monthly-admin',
    billingCycle: 'monthly',
    category: 'service',
    dependsOn: 'lifetime_inr',
  },
];







