// All plans (USD and INR, with currency field)
export const plans = [
  // USD plans
  {
    id: 'lifetime',
    name: 'Lifetime Membership',
    price: 25,
    priceNumeric: 25,
    currency: 'USD',
    description: 'Permanent membership required to purchase any other plan. One-time payment, allows access to all other plans.',
    features: [
      'Personal onboarding with Z',
      'Resume intake & profile setup',
      'Expert profile review',
      'Fast, secure data handling',
      'Permanent membership (one-time payment)'
    ],
    billing: 'one-time',
    billingCycle: 'one-time',
    category: 'membership',
    validity: 'lifetime',
  },
  // USA plans
  {
    id: 'payg',
    name: 'Pay-As-You-Go',
    price: 0,
    currency: 'USD',
    description: 'Monthly postpaid plan. $2 per application, $3 per approved application. Bill is generated based on number of hot jobs applied and approved.',
    features: [
      'Z applies for you',
      '$2 per application',
      '$3 per approved application',
      'Live status tracking'
    ],
    billing: 'monthly-postpaid',
    billingCycle: 'monthly',
    category: 'service',
    pricing: { perApplication: 2, perApproved: 3, currency: 'USD' },
    dependsOn: 'lifetime',
  },
  {
    id: 'pro_month_usd',
    name: 'Pro (One Month)',
    price: 500,
    currency: 'USD',
    description: 'Monthly plan for serious job hunters. Up to 300 hot jobs apply per month.',
    features: [
      'Up to 300 hot jobs applications/month',
      'Advanced resume tailoring',
      '1:1 onboarding call',
      'Priority support'
    ],
    billing: 'monthly',
    billingCycle: 'monthly',
    category: 'service',
    dependsOn: 'lifetime',
  },
  {
    id: 'elite_usd',
    name: 'Elite Add-Ons',
    price: 10000,
    currency: 'USD',
    description: 'Monthly plan. Premium features for maximum success. Bill generated by admin.',
    features: [
      'Ask Z: HR Q&A agent',
      'Resume AI chatbot',
      'Interview Cohort coaching',
      'Early access to new AI'
    ],
    billing: 'monthly-admin',
    billingCycle: 'monthly',
    category: 'service',
    dependsOn: 'lifetime',
  },
  // INR plans
  {
    id: 'payg_inr',
    name: 'Pay-As-You-Go',
    price: 20,
    currency: 'INR',
    description: 'Monthly postpaid plan. ₹20 per application, ₹30 per approved application. Bill is generated based on number of hot jobs applied and approved.',
    features: [
      'Z applies for you',
      '₹20 per application',
      '₹30 per approved application',
      'Live status tracking'
    ],
    billing: 'monthly-postpaid',
    billingCycle: 'monthly',
    category: 'service',
    pricing: { perApplication: 20, perApproved: 30, currency: 'INR' },
    dependsOn: 'lifetime_inr',
  },
  // INR plans
  {
    id: 'lifetime_inr',
    name: 'Lifetime Membership',
    price: 199,
    priceNumeric: 199,
    currency: 'INR',
    description: 'Permanent membership required to purchase any other plan. One-time payment, allows access to all other plans.',
    features: [
      'Personal onboarding with Z',
      'Resume intake & profile setup',
      'Expert profile review',
      'Fast, secure data handling',
      'Permanent membership (one-time payment)'
    ],
    billing: 'one-time',
    billingCycle: 'one-time',
    category: 'membership',
    validity: 'lifetime',
  },
  {
    id: 'pro_month',
    name: 'Pro (One Month)',
    price: 99,
    currency: 'INR',
    description: 'Monthly plan for serious job hunters. Up to 300 hot jobs apply per month.',
    features: [
      'Up to 300 hot jobs applications/month',
      'Advanced resume tailoring',
      '1:1 onboarding call',
      'Priority support'
    ],
    billing: 'monthly',
    billingCycle: 'monthly',
    category: 'service',
    dependsOn: 'lifetime_inr',
  },
  {
    id: 'elite',
    name: 'Elite Add-Ons',
    price: 10000,
    currency: 'INR',
    description: 'Monthly plan. Premium features for maximum success. Bill generated by admin.',
    features: [
      'Ask Z: HR Q&A agent',
      'Resume AI chatbot',
      'Interview Cohort coaching',
      'Early access to new AI'
    ],
    billing: 'monthly-admin',
    billingCycle: 'monthly',
    category: 'service',
    dependsOn: 'lifetime_inr',
  },
];
